name: PHP Lint

on: [pull_request]

jobs:
  php_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check Docker version
        run: docker --version

      - name: Run Docker Compose
        run: docker-compose up -d

